FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/.next/standalone /usr/share/nginx/html
COPY --from=builder /app/public /usr/share/nginx/html/public
COPY --from=builder /app/.next/static /usr/share/nginx/html/.next/static
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
